user = User.create!(:email => "admin@example.com", :password => 'password', :password_confirmation => 'password')
user_role = user.user_roles.create!(:role => "admin")
page = Page.create!(:title => "Home", :body => "Hello World!")
menu = Menu.create!(:name => "main_menu", :display_name => "Main Menu")
menu_item = MenuItem.create!(:title => page.title, :page_id => page.id, :menu_id => menu.id)
